### ISSUE TITLE
CW308T_LPC1343F - missing gerber files

### ISSUE THREAD

**Issue by lukaskuzmiak** [newaetech/chipwhisperer-target-cw308t#3]
There seems to be a `.PcbDoc` there but no gerbers. I'm opening this as suggested by @colinoflynn on Twitter.

If the board was untested I will be happy to have these made once gerbers are available and test them out.

**Comment by colinoflynn** [comment]
So there was some error in rev 01, I was trying to find an old PCB here but failed. IIRC the boot pin was routed incorrectly, but there has been a rev02 PCB design in there for a while so I believe it was fixed in the design. But I can't find the flywired board here to confirm this.

So I just generated gerbers & committed them. I don't think they have ever been tested, but the hacked PCB here (which just flywired the pin) did work from memory. Unfortunately I can't guarantee much more than that!
