### ISSUE TITLE
N76E003 target board

### ISSUE THREAD

**Issue by nikitalita** [newaetech/chipwhisperer-target-cw308t#7]
I have the target board for the N76E003 (and other NuMicro 1T 8051 chips) ready to be PRed here:
https://github.com/nikitalita/n76e003-ufo-target-board

However, the board is made in KiCad, and I notice everything here is made in Altium. I don't want to shell out for an Altium license; is it possible to just submit the KiCad files, or would you want to convert this to Altium yourselves?

Below are the pics of the board and the schematics:

<img width="696" alt="image" src="https://github.com/newaetech/chipwhisperer-target-cw308t/assets/69168929/b60fbe68-6887-4bb1-8d78-14fc52c5a753">
<img width="1335" alt="image" src="https://github.com/newaetech/chipwhisperer-target-cw308t/assets/69168929/b90fab22-44f1-4f68-98f5-0c79e9e7e0c3">

**Comment by colinoflynn** [comment]
Amazing, thanks so much! Please PR as-is, yes the Altium source was a bit of a historical debt rather than something we actively encourage/prefer ;-) Eventually we may try to convert some to KiCad so they can be more easily modified.... for now we're going to be switching going forward on some new projects as we slowly drop Altium ourselves.
